myFunction([
{
"accountName": "Sales of Product Income",
"connected": "False",
"description": "The gs-150 digital bathroom scale features a tempered glass weighing platform with an easy to read lcd. this scale features an auto on function; no tapping required.",
"id": "1101",
"inventory": "True",
"isConnected": "False",
"isInactive": "False",
"name": "Tempered Glass Digital Bathroom Scale",
"numOfAllChildren": "0",
"purchaseAmount": "",
"purchaseRateTaxInclusive": "False",
"purchases": "True",
"qoh": "12",
"reverseChargeRate": "",
"sales": "True",
"salesAmount": "15.18",
"salesRateTaxInclusive": "False",
"subLevel": "1",
"trackInventory": "True"
},
{
"accountName": "Sales of Product Income",
"connected": "False",
"description": "This is one of 2,500 highly collectible 2009 USDGC fundraiser champion Rocs. The Roc is simply the best, most versatile mid-range disc ever made. It provides accuracy at any range. ",
"id": "1102",
"inventory": "True",
"isConnected": "False",
"isInactive": "False",
"name": "Innova Champion San Marino",
"numOfAllChildren": "0",
"purchaseAmount": "",
"purchaseRateTaxInclusive": "False",
"purchases": "True",
"qoh": "11",
"reverseChargeRate": "",
"sales": "True",
"salesAmount": "34",
"salesRateTaxInclusive": "False",
"subLevel": "1",
"trackInventory": "True"
},
{
"accountName": "Sales of Product Income",
"connected": "False",
"description": "TWith this Sunbeam Dial Scale, you get the tools you need without taking up space. This classic scale has a compact footprint, making it ideal for small bathrooms.",
"id": "1103",
"inventory": "True",
"isConnected": "False",
"isInactive": "False",
"name": "Sunbeam White Dial Scale",
"numOfAllChildren": "0",
"purchaseAmount": "",
"purchaseRateTaxInclusive": "False",
"purchases": "True",
"qoh": "12",
"reverseChargeRate": "",
"sales": "True",
"salesAmount": "11.68",
"salesRateTaxInclusive": "False",
"subLevel": "1",
"trackInventory": "True"
},
{
"accountName": "Sales of Product Income",
"connected": "False",
"description": "Finally. A nutrition shake for women that satisfies hunger while providing real results. FitMiss Delight brings a full day's essential nutrients with quality calories and delivers optimal levels of protein, digestive enzymes, vitamins and minerals. ",
"id": "4",
"inventory": "True",
"isConnected": "False",
"isInactive": "False",
"name": "Fitmiss Delight Nutritional Shake",
"numOfAllChildren": "0",
"purchaseAmount": "",
"purchaseRateTaxInclusive": "False",
"purchases": "True",
"qoh": "9",
"reverseChargeRate": "",
"sales": "True",
"salesAmount": "85.99",
"salesRateTaxInclusive": "False",
"subLevel": "1",
"trackInventory": "True"
},
{
"accountName": "Sales of Product Income",
"connected": "False",
"description": "Tired of parting hair into quarter-inch rows to apply hair color? Simplify your home hair care routine. With COMB-A-COLOR perfect at home hair color is just a squeeze, and comb a color away! Its easy, just pour your favorite hair color into the supplied squeeze bottle, and attach COMB-A-COLOR applicator.",
"id": "1105",
"inventory": "True",
"isConnected": "False",
"isInactive": "False",
"name": "Quick Hair Color Applicator",
"numOfAllChildren": "0",
"purchaseAmount": "",
"purchaseRateTaxInclusive": "False",
"purchases": "True",
"qoh": "12",
"reverseChargeRate": "",
"sales": "True",
"salesAmount": "4.20",
"salesRateTaxInclusive": "False",
"subLevel": "1",
"trackInventory": "True"
},
{
"accountName": "Sales of Product Income",
"connected": "False",
"description": "ColorMe Professional offers the most versatile and intense colors available in a temporary hair color.",
"id": "1106",
"inventory": "True",
"isConnected": "False",
"isInactive": "False",
"name": "Colorme Temporary Hair Color Blue Escape",
"numOfAllChildren": "0",
"purchaseAmount": "",
"purchaseRateTaxInclusive": "False",
"purchases": "True",
"qoh": "12",
"reverseChargeRate": "",
"sales": "True",
"salesAmount": "6.50",
"salesRateTaxInclusive": "False",
"subLevel": "1",
"trackInventory": "True"
},
{
"accountName": "Sales of Product Income",
"connected": "False",
"description": "ColorMe Professional offers the most versatile and intense colors available in a temporary hair color.",
"id": "1107",
"inventory": "True",
"isConnected": "False",
"isInactive": "False",
"name": "ColorMe by Giuliano",
"numOfAllChildren": "0",
"purchaseAmount": "",
"purchaseRateTaxInclusive": "False",
"purchases": "True",
"qoh": "5",
"reverseChargeRate": "",
"sales": "True",
"salesAmount": "6.50",
"salesRateTaxInclusive": "False",
"subLevel": "1",
"trackInventory": "True"
},
{
"accountName": "Sales of Product Income",
"connected": "False",
"description": "This is a very beautiful",
"id": "8",
"inventory": "True",
"isConnected": "False",
"isInactive": "False",
"name": "Car Accessories: Place holder",
"numOfAllChildren": "0",
"purchaseAmount": "",
"purchaseRateTaxInclusive": "False",
"purchases": "True",
"qoh": "12",
"reverseChargeRate": "",
"sales": "True",
"salesAmount": "32",
"salesRateTaxInclusive": "False",
"subLevel": "1",
"trackInventory": "True"
},
{
"accountName": "Sales of Product Income",
"connected": "False",
"description": "This is a very beautiful",
"id": "9",
"inventory": "True",
"isConnected": "False",
"isInactive": "False",
"name": "Car Accessories: Place holder",
"numOfAllChildren": "0",
"purchaseAmount": "",
"purchaseRateTaxInclusive": "False",
"purchases": "True",
"qoh": "12",
"reverseChargeRate": "",
"sales": "True",
"salesAmount": "32",
"salesRateTaxInclusive": "False",
"subLevel": "1",
"trackInventory": "True"
}
])